# Django otomatik algilamayi devre disi birak
providers = []

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

# Build asamasinda migrate/collectstatic CALISTIRMA (runtime'da calisacak)
[phases.build]
cmds = []

[start]
cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn core.wsgi --bind 0.0.0.0:$PORT"
