# Generated by Django 5.1.2 on 2025-10-30 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=64)),
                ('entity_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=32)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, max_length=128, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicil_no', models.CharField(max_length=64, unique=True)),
                ('ad', models.CharField(max_length=128)),
                ('soyad', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisi_sicilno', models.CharField(max_length=64)),
                ('ad', models.CharField(max_length=128)),
                ('soyad', models.CharField(max_length=128)),
                ('telno', models.CharField(blank=True, max_length=64, null=True)),
                ('mail', models.EmailField(blank=True, max_length=256, null=True)),
                ('ilce', models.CharField(blank=True, max_length=128, null=True)),
                ('adres_aciklama', models.TextField(blank=True, null=True)),
                ('notlar', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cevap_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.statusoption')),
            ],
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=512)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('STAGED', 'STAGED'), ('APPLIED', 'APPLIED'), ('REJECTED', 'REJECTED')], default='STAGED', max_length=16)),
                ('created_by', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='BatchDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_count', models.IntegerField(default=0)),
                ('removed_count', models.IntegerField(default=0)),
                ('changed_count', models.IntegerField(default=0)),
                ('diff_json', models.JSONField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uploadbatch')),
            ],
        ),
        migrations.CreateModel(
            name='UploadRowStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisi_sicilno', models.CharField(max_length=64)),
                ('ad', models.CharField(max_length=128)),
                ('soyad', models.CharField(max_length=128)),
                ('telno', models.CharField(blank=True, max_length=64, null=True)),
                ('mail', models.CharField(blank=True, max_length=256, null=True)),
                ('ilce', models.CharField(blank=True, max_length=128, null=True)),
                ('adres_aciklama', models.TextField(blank=True, null=True)),
                ('notlar', models.TextField(blank=True, null=True)),
                ('cevap_status_key', models.CharField(blank=True, max_length=64, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uploadbatch')),
            ],
        ),
        migrations.CreateModel(
            name='LawyerPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisi_sicilno_copy', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lawyer')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
            options={
                'indexes': [models.Index(fields=['lawyer'], name='app_lawyerp_lawyer__c8e8e4_idx')],
                'unique_together': {('lawyer', 'kisi_sicilno_copy')},
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['kisi_sicilno'], name='app_person_kisi_si_a53412_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['ad', 'soyad'], name='app_person_ad_744d6c_idx'),
        ),
    ]
