# Generated by Django 5.1.2 on 2025-10-31 08:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisi_sicilno', models.CharField(max_length=64)),
                ('ad', models.CharField(blank=True, default='', max_length=128)),
                ('soyad', models.CharField(blank=True, default='', max_length=128)),
                ('telno', models.CharField(blank=True, default='', max_length=64)),
                ('mail', models.EmailField(blank=True, default='', max_length=254)),
                ('ilce', models.CharField(blank=True, default='', max_length=128)),
                ('adres_aciklama', models.TextField(blank=True, default='')),
                ('notlar', models.TextField(blank=True, default='')),
                ('cevap_status_key', models.CharField(blank=True, default='', max_length=64)),
                ('row_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app.uploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'kisi_sicilno'], name='app_uploadr_batch_i_ad0d90_idx')],
            },
        ),
    ]
