# Generated by Django 5.1.2 on 2025-11-07 09:50

import django.db.models.deletion
from django.db import migrations, models


def copy_person_data_to_lawyerperson(apps, schema_editor):
    """
    Person tablosundaki verileri LawyerPerson'a kopyala.
    Her LawyerPerson kaydı için bağlı Person'dan verileri al.
    """
    LawyerPerson = apps.get_model('app', 'LawyerPerson')
    Person = apps.get_model('app', 'Person')

    for lp in LawyerPerson.objects.all().select_related('person'):
        if lp.person:
            # Person'dan verileri kopyala
            lp.kisi_sicilno = lp.person.kisi_sicilno or ''
            lp.ad = lp.person.ad or ''
            lp.soyad = lp.person.soyad or ''
            lp.telno = lp.person.telno
            lp.mail = lp.person.mail
            lp.ilce = lp.person.ilce
            lp.adres_aciklama = lp.person.adres_aciklama
            lp.notlar = lp.person.notlar
            lp.cevap_status_id = lp.person.cevap_status_id
            lp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadrow'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lawyerperson',
            name='app_lawyerp_lawyer__c8e8e4_idx',
        ),
        migrations.AddField(
            model_name='lawyerperson',
            name='ad',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='lawyerperson',
            name='adres_aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerperson',
            name='cevap_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.statusoption'),
        ),
        migrations.AddField(
            model_name='lawyerperson',
            name='ilce',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='lawyerperson',
            name='kisi_sicilno',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lawyerperson',
            name='mail',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lawyerperson',
            name='notlar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerperson',
            name='soyad',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='lawyerperson',
            name='telno',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        # Verileri kopyala
        migrations.RunPython(copy_person_data_to_lawyerperson, reverse_code=migrations.RunPython.noop),
        # Sonra unique_together değiştir (artık kisi_sicilno dolu)
        migrations.AlterUniqueTogether(
            name='lawyerperson',
            unique_together={('lawyer', 'kisi_sicilno')},
        ),
        migrations.AddIndex(
            model_name='lawyerperson',
            index=models.Index(fields=['lawyer', 'active'], name='app_lawyerp_lawyer__0332ed_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyerperson',
            index=models.Index(fields=['kisi_sicilno'], name='app_lawyerp_kisi_si_251b9d_idx'),
        ),
        # Eski kisi_sicilno_copy alanını kaldır (artık gerekli değil)
        migrations.RemoveField(
            model_name='lawyerperson',
            name='kisi_sicilno_copy',
        ),
    ]
