# Generated by Django 5.1.2 on 2025-11-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_lawyerperson_app_lawyerp_lawyer__c8e8e4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Seçim adı (örn: Ön Seçim 2025, Ana Seçim 2025)', max_length=256)),
                ('election_date', models.DateField(help_text='Seçim tarihi')),
                ('is_active', models.BooleanField(default=False, help_text='Aktif seçim günü (sadece bir seçim aktif olabilir)')),
                ('allow_external_registration', models.BooleanField(default=True, help_text='Dışarıdan kayıt kabul edilsin mi?')),
                ('description', models.TextField(blank=True, help_text='Seçim açıklaması', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-election_date'],
                'indexes': [models.Index(fields=['is_active'], name='app_electio_is_acti_1b08b6_idx'), models.Index(fields=['election_date'], name='app_electio_electio_08e176_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_voted', models.BooleanField(default=False, help_text='Oy verdi mi?')),
                ('voted_at', models.DateTimeField(blank=True, help_text='Oy verme zamanı', null=True)),
                ('recorded_by', models.CharField(blank=True, help_text='Kaydı yapan görevli', max_length=256, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notlar', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.election')),
                ('lawyerperson', models.ForeignKey(help_text='Oy veren kişi', on_delete=django.db.models.deletion.CASCADE, to='app.lawyerperson')),
            ],
            options={
                'indexes': [models.Index(fields=['election', 'has_voted'], name='app_electio_electio_142f98_idx'), models.Index(fields=['election', 'lawyerperson'], name='app_electio_electio_6bf2a3_idx')],
                'unique_together': {('election', 'lawyerperson')},
            },
        ),
    ]
