# Generated by Django 5.1.2 on 2025-12-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_election_electionvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaroLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicil_no', models.CharField(db_index=True, help_text='Avukat sicil numarası', max_length=64, unique=True)),
                ('ad', models.CharField(help_text='Avukat adı', max_length=128)),
                ('soyad', models.CharField(help_text='Avukat soyadı', max_length=128)),
                ('tel', models.CharField(blank=True, default='', help_text='Telefon numarası', max_length=64)),
                ('mail', models.EmailField(blank=True, default='', help_text='E-posta adresi', max_length=256)),
                ('adres', models.TextField(blank=True, default='', help_text='Adres bilgisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Baro Avukatı',
                'verbose_name_plural': 'Baro Avukatları',
                'ordering': ['sicil_no'],
                'indexes': [models.Index(fields=['sicil_no'], name='app_barolaw_sicil_n_7e8f47_idx'), models.Index(fields=['ad', 'soyad'], name='app_barolaw_ad_fbcdbd_idx'), models.Index(fields=['mail'], name='app_barolaw_mail_36e333_idx')],
            },
        ),
    ]
