# Generated by Django 5.1.2 on 2025-12-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_barolawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
