# Generated by Django 5.1.2 on 2026-02-22 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_uploadbatch_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('data_uploader', 'Veri Yukleyici'), ('read_only', 'Sadece Okuma')], default='read_only', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanici Profili',
                'verbose_name_plural': 'Kullanici Profilleri',
            },
        ),
        migrations.CreateModel(
            name='LawyerAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Kodun gecerlilik suresi')),
                ('is_active', models.BooleanField(default=True, help_text='Kod aktif mi?')),
                ('use_count', models.IntegerField(default=0, help_text='Kod kac kez kullanildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_codes', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='app.election')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='app.lawyer')),
            ],
            options={
                'verbose_name': 'Avukat Erisim Kodu',
                'verbose_name_plural': 'Avukat Erisim Kodlari',
                'indexes': [models.Index(fields=['code'], name='app_lawyera_code_e93a83_idx'), models.Index(fields=['lawyer', 'election'], name='app_lawyera_lawyer__80ad56_idx'), models.Index(fields=['is_active', 'expires_at'], name='app_lawyera_is_acti_454066_idx')],
            },
        ),
    ]
