# Generated by Django 5.1.2 on 2026-03-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_auth_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaroLawyerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('blacklist', 'Kara Liste'), ('whitelist', 'Biz')], max_length=16)),
                ('note', models.TextField(blank=True, help_text='Etiketleme nedeni / not', null=True)),
                ('created_by', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baro_lawyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='app.barolawyer')),
            ],
            options={
                'verbose_name': 'Baro Avukat Etiketi',
                'verbose_name_plural': 'Baro Avukat Etiketleri',
                'indexes': [models.Index(fields=['tag_type'], name='app_barolaw_tag_typ_e7d826_idx')],
            },
        ),
    ]
