# Generated by Django 5.1.2 on 2026-03-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_barolawyertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='barolawyer',
            name='cinsiyet',
            field=models.CharField(blank=True, default='', help_text='Cinsiyeti (E/K)', max_length=8),
        ),
        migrations.AddField(
            model_name='barolawyer',
            name='dogum_tarihi',
            field=models.CharField(blank=True, default='', help_text='Doğum tarihi', max_length=64),
        ),
        migrations.AddField(
            model_name='barolawyer',
            name='dogum_yeri',
            field=models.CharField(blank=True, default='', help_text='Doğum yeri', max_length=128),
        ),
        migrations.AddField(
            model_name='barolawyer',
            name='ilce',
            field=models.CharField(blank=True, default='', help_text='İlçe', max_length=128),
        ),
        migrations.AddField(
            model_name='barolawyer',
            name='mahalle_koy',
            field=models.CharField(blank=True, default='', help_text='Mahalle/Köy', max_length=128),
        ),
        migrations.AddField(
            model_name='barolawyer',
            name='mesleğe_baslama',
            field=models.CharField(blank=True, default='', help_text='Mesleğe başlama tarihi', max_length=64),
        ),
        migrations.AddField(
            model_name='barolawyer',
            name='nufus_il',
            field=models.CharField(blank=True, default='', help_text='Nüfus il', max_length=128),
        ),
        migrations.AddField(
            model_name='barolawyer',
            name='nufus_ilce',
            field=models.CharField(blank=True, default='', help_text='Nüfus ilçe', max_length=128),
        ),
        migrations.AddField(
            model_name='barolawyer',
            name='uye',
            field=models.CharField(blank=True, default='', help_text='Üyelik durumu (Aktif/Pasif)', max_length=64),
        ),
        migrations.AlterField(
            model_name='barolawyertag',
            name='tag_type',
            field=models.CharField(choices=[('blacklist', 'Kara Liste'), ('whitelist', 'Beyaz Liste')], max_length=16),
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorev', models.CharField(help_text='Görev/Kurul adı', max_length=256)),
                ('sicil_no', models.CharField(db_index=True, help_text='Avukat sicil numarası', max_length=64)),
                ('ad_soyad', models.CharField(help_text='Ad Soyad', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baro_lawyer', models.ForeignKey(blank=True, help_text='Baro kaydı (varsa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='app.barolawyer')),
            ],
            options={
                'verbose_name': 'Kurul Üyeliği',
                'verbose_name_plural': 'Kurul Üyelikleri',
                'ordering': ['ad_soyad', 'gorev'],
                'indexes': [models.Index(fields=['sicil_no'], name='app_committ_sicil_n_8eaf28_idx'), models.Index(fields=['gorev'], name='app_committ_gorev_b7f04a_idx')],
            },
        ),
    ]
