# Generated by Django 5.1.2 on 2026-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_barolawyer_cinsiyet_barolawyer_dogum_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemembership',
            name='gorev',
            field=models.CharField(help_text='Görev/Kurul adı', max_length=512),
        ),
    ]
