# Generated by Django 5.1.2 on 2026-03-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_committeemembership_gorev'),
    ]

    operations = [
        migrations.AddField(
            model_name='barolawyer',
            name='photo_url',
            field=models.URLField(blank=True, default='', help_text='Baro profil fotoğrafı URL', max_length=512),
        ),
    ]
